# Generated by Django 2.0.4 on 2018-05-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=200)),
                ('workout_type', models.PositiveIntegerField(choices=[(1, 'Aerobic exercise'), (2, 'Strength exercise'), (3, 'Balance exercise'), (4, 'Flexibility exercise')], default=None)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('workout_photo', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
