# Generated by Django 2.0.4 on 2018-05-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=200)),
                ('workout_type', models.CharField(choices=[('Aerobic exercise', 'Aerobic exercise'), ('Strength exercise', 'Strength exercise'), ('Balance exercise', 'Balance exercise'), ('Flexibility exercise', 'Flexibility exercise')], max_length=20)),
                ('workout_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
