# Generated by Django 2.0.4 on 2018-05-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workout_description',
            new_name='description',
        ),
    ]
