# Generated by Django 2.0.4 on 2018-05-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20180516_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
