# Generated by Django 2.0.5 on 2018-05-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workout_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='image',
            new_name='workout_photo',
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.IntegerField(choices=[(1, 'Aerobic exercise'), (2, 'Strength exercise'), (3, 'Balance exercise'), (4, 'Flexibility exercise')], default=None),
        ),
    ]
