# Generated by Django 2.0.4 on 2018-05-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20180518_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.IntegerField(choices=[(1, 'Aerobic exercise'), (2, 'Strength exercise'), (3, 'Balance exercise'), (4, 'Flexibility exercise')]),
        ),
    ]
