# Generated by Django 2.0.4 on 2018-05-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usertype',
            field=models.PositiveIntegerField(choices=[(1, 'Trainee'), (2, 'Trainer')], default=None),
        ),
    ]
