# Generated by Django 2.0.5 on 2018-05-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[('Trainee', 'Trainee'), ('Trainer', 'Trainer')], default='Trainee', max_length=7),
        ),
    ]
