# Generated by Django 2.0.5 on 2018-05-23 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='userprofile.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=200)),
                ('workout_type', models.IntegerField(choices=[(1, 'Aerobic exercise'), (2, 'Strength exercise'), (3, 'Balance exercise'), (4, 'Flexibility exercise')], default=None)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('workout_photo', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
